variable "region" {}
variable "bastion_hosts" {}
variable "network_security_groups" {}
variable "public_ip_addresses" {}
variable "resource_group_names" {}
variable "virtual_network_peerings" {}
variable "virtual_networks" {}
variable "subnets" {}
variable "tags" {}